# Sidebar navigation

- label: 'Overview'
  link: '/'
- label: 'Installation'
  link: '/installation'
- label: 'Quick start'
  link: '/quick-start'
- label: 'API reference'
  items:
    - label: 'useField'
      link: '/api/use-field'
    - label: 'Scope'
      link: '/api/scope'

- label: Guides
  items:
    - label: 'Basic form'
      link: '/guides/basic-form'
    - label: 'React Native'
      link: '/guides/react-native'
    - label: 'Initial data'
      link: '/guides/initial-data'
    - label: 'Complex structures'
      link: '/guides/complex-structures'
    - label: 'Validation'
      link: '/guides/validation'
    - label: 'Get/set field value'
      link: '/guides/get-set-field-value'
    - label: 'Get/set field error'
      link: '/guides/get-set-field-error'
    - label: 'Reset form'
      link: '/guides/reset-form'
    - label: 'Manual form submit'
      link: '/guides/manual-form-submit'

- label: Recipes
  items:
    - label: 'Simple Input'
      link: '/recipes/simple-input'
    - label: 'Accessing form ref'
      link: '/recipes/accessing-form-ref'
    - label: 'Accessing field ref'
      link: '/recipes/accessing-field-ref'
    - label: 'Styled Components'
      link: '/recipes/styled-components'
    - label: 'Clear input error on focus'
      link: '/recipes/clear-input-error-on-focus'
    - label: 'Accessing form event'
      link: '/recipes/accessing-form-event'
    - label: 'TypeScript'
      link: '/recipes/typescript'

- label: Examples
  items:
    - label: 'File input'
      link: '/examples/file-input'
    - label: 'React Select'
      link: '/examples/react-select'
    - label: 'React DatePicker'
      link: '/examples/react-datepicker'
    - label: 'React Dropzone'
      link: '/examples/react-dropzone'
    - label: 'React Simple Code Editor'
      link: '/examples/react-simple-code-editor'
    - label: 'React Input Mask'
      link: '/examples/react-input-mask'
    - label: 'React Native Input Mask'
      link: '/examples/react-native-input-mask'
    - label: 'React Native Picker Select'
      link: '/examples/react-native-picker-select'
    - label: 'More Examples'
      link: '/examples/more-examples'

- label: More
  items:
    - label: Roadmap
      link: '/roadmap'
    - label: 'Migration guide'
      link: '/migration-guide'
    - label: 'Github'
      link: 'https://github.com/unform/unform'
    - label: 'React Demo'
      link: 'https://codesandbox.io/embed/agitated-tdd-uf177?autoresize=1&expanddevtools=1&fontsize=14&hidenavigation=1&theme=dark'
    - label: 'React Native Demo'
      link: 'https://snack.expo.io/@diego3g/1e9fb3'
