
name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
  env:
    GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install Dependencies
        run: yarn --1.22.15
        
      - name: Coveralls
        uses: coverallsapp/github-action@master



        

        


