on: ["push","pull_request"]

name: build

jobs:
  test:
    runs-on: ubuntu-latest
    env:
     github-token: ${{ secrets.GITHUB_TOKEN }}
   
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          version: 10.x
      - run: npm install mocha-lcov-reporter --save-dev
      - name: Coveralls
        uses: coverallsapp/github-action@v1.1.0
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          flag-name: run-${{ matrix.test_number }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v1.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
